# Generated by Django 5.1.3 on 2025-01-14 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('comuna_id', models.AutoField(primary_key=True, serialize=False)),
                ('comuna', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='DeptoEmpresa',
            fields=[
                ('depto_id', models.AutoField(primary_key=True, serialize=False)),
                ('depto', models.CharField(db_column='depto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('estcivil_id', models.AutoField(primary_key=True, serialize=False)),
                ('estadocivil', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estadocivil',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sexo_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sexo',
            },
        ),
        migrations.CreateModel(
            name='TipoAusentismo',
            fields=[
                ('tipoausen_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(db_column='tipo', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('cargo_id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(db_column='cargo', max_length=50)),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.deptoempresa')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('empresa_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(db_column='rut', max_length=8, unique=True, verbose_name='Rut')),
                ('dvRut', models.CharField(db_column='dvRut', max_length=1, verbose_name='Digito Verificador')),
                ('razonSocial', models.CharField(db_column='razonSocial', max_length=100, verbose_name='Razón Social')),
                ('nombreFant', models.CharField(blank=True, db_column='nombreFant', max_length=100, null=True, verbose_name='Nombre de fantasía')),
                ('giro', models.CharField(db_column='giro', max_length=150, verbose_name='Giro')),
                ('direccion', models.CharField(db_column='direccion', max_length=150, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=11, null=True, verbose_name='Teléfono')),
                ('comuna_id', models.ForeignKey(blank=True, db_column='comuna_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.comuna', verbose_name='Comuna')),
                ('region_id', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.region', verbose_name='Región')),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('personal_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=8, unique=True)),
                ('dvrut', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
                ('apepat', models.CharField(max_length=50)),
                ('apemat', models.CharField(max_length=50)),
                ('fechanac', models.DateField(blank=True, null=True)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=150, null=True)),
                ('comuna_id', models.ForeignKey(blank=True, db_column='comuna_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.comuna')),
                ('estcivil_id', models.ForeignKey(blank=True, db_column='estcivil_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.estadocivil')),
                ('region_id', models.ForeignKey(blank=True, db_column='region_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.region')),
                ('sexo_id', models.ForeignKey(blank=True, db_column='sexo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.sexo')),
            ],
            options={
                'db_table': 'Personal',
            },
        ),
        migrations.CreateModel(
            name='InfoLaboral',
            fields=[
                ('infolab_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechacontrata', models.DateField()),
                ('cargo_id', models.ForeignKey(db_column='cargo_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.cargo')),
                ('depto_id', models.ForeignKey(db_column='depto_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.deptoempresa')),
                ('empresa_id', models.ForeignKey(db_column='empresa_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.empresa')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='region_id',
            field=models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.region'),
        ),
        migrations.CreateModel(
            name='Ausentismo',
            fields=[
                ('ausentismo_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaini', models.DateField()),
                ('fechafin', models.DateField()),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('tipoausen_id', models.ForeignKey(db_column='tipoausen_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoausentismo')),
            ],
        ),
    ]
