# Generated by Django 5.1.3 on 2025-01-19 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaseLicencia',
            fields=[
                ('claseLicencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('claseLicencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('resultadoEx_id', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCertificacion',
            fields=[
                ('tipoCertificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoCertificacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClasificacion',
            fields=[
                ('tipoClasi_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('tipoEx_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoExamen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('tipoLicencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('tipoLicencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('proveedor_id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.IntegerField(max_length=8)),
                ('dvRut', models.IntegerField(max_length=1)),
                ('razonSocial', models.CharField(max_length=100)),
                ('nombreFant', models.CharField(blank=True, max_length=100, null=True)),
                ('giro', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna_id', models.ForeignKey(db_column='comuna_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.comuna')),
                ('region_id', models.ForeignKey(db_column='region_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.region')),
            ],
        ),
        migrations.CreateModel(
            name='Certificacion',
            fields=[
                ('certif_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.CharField(max_length=256)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('tipoCertificacion_id', models.ForeignKey(db_column='tipoCertificacion_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipocertificacion')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionProveedor',
            fields=[
                ('clasifProv_id', models.AutoField(primary_key=True, serialize=False)),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('tipoClasi_id', models.ForeignKey(db_column='tipoClasi_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoclasificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('examen_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.CharField(max_length=256)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('proveedor_id', models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.proveedor')),
                ('resultadoEx_id', models.ForeignKey(db_column='resultadoEx_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.resultadoexamen')),
                ('tipoEx_id', models.ForeignKey(db_column='tipoEx_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='LicenciaPorPersonal',
            fields=[
                ('licenciaPorPersonal_id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaEmision', models.DateField()),
                ('fechaVencimiento', models.DateField()),
                ('rutaDoc', models.CharField(max_length=256)),
                ('observacion', models.TextField(blank=True, max_length=250, null=True)),
                ('claseLicencia_id', models.ForeignKey(db_column='claseLicencia_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.claselicencia')),
                ('personal_id', models.ForeignKey(db_column='personal_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.personal')),
                ('tipoLicencia_id', models.ForeignKey(db_column='tipoLicencia_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipolicencia')),
            ],
        ),
        migrations.AddField(
            model_name='claselicencia',
            name='tipoLicencia_id',
            field=models.ForeignKey(db_column='tipoLicencia_id', on_delete=django.db.models.deletion.CASCADE, to='rrhh_personal.tipolicencia'),
        ),
    ]
