# Generated by Django 5.1.3 on 2025-01-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0003_alter_proveedor_dvrut_alter_proveedor_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacion',
            name='rutaDoc',
            field=models.FileField(upload_to='Documentos/Certificaciones'),
        ),
        migrations.AlterField(
            model_name='licenciaporpersonal',
            name='rutaDoc',
            field=models.FileField(upload_to='Documentos/Licencias'),
        ),
    ]
