# Generated by Django 5.1.2 on 2025-01-20 14:41

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0004_alter_certificacion_rutadoc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciaporpersonal',
            name='rutaDoc',
            field=models.FileField(upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
    ]
