# Generated by Django 5.1.3 on 2025-01-29 23:02

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0005_alter_licenciaporpersonal_rutadoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacion',
            name='rutaDoc',
            field=models.FileField(upload_to='Certificaciones'),
        ),
        migrations.AlterField(
            model_name='licenciaporpersonal',
            name='rutaDoc',
            field=models.FileField(storage=rrhh_personal.models.OverwriteStorage, upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
    ]
