# Generated by Django 5.1.3 on 2025-02-24 01:23

import rrhh_personal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rrhh_personal', '0007_alter_examen_rutadoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacion',
            name='rutaDoc',
            field=models.FileField(upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
        migrations.AlterField(
            model_name='examen',
            name='rutaDoc',
            field=models.FileField(upload_to=rrhh_personal.models.obtener_ruta_documento),
        ),
    ]
