# Generated by Django 5.0.6 on 2025-03-26 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcaeq', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['marcaeq'],
            },
        ),
        migrations.CreateModel(
            name='TipoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefixeq', models.CharField(max_length=2, unique=True)),
                ('tipoeq', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo equipo',
                'verbose_name_plural': 'Tipo equipos',
                'ordering': ['tipoeq'],
            },
        ),
        migrations.CreateModel(
            name='ModeloEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modeloeq', models.CharField(max_length=150)),
                ('marcaeq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.marcaequipo')),
                ('tipoeq', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.tipoequipo')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'ordering': ['modeloeq'],
            },
        ),
        migrations.AddField(
            model_name='marcaequipo',
            name='tipoeq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.tipoequipo'),
        ),
        migrations.AddConstraint(
            model_name='modeloequipo',
            constraint=models.UniqueConstraint(fields=('tipoeq', 'marcaeq', 'modeloeq'), name='unique_tipoeq_marcaeq_modeloeq'),
        ),
        migrations.AddConstraint(
            model_name='marcaequipo',
            constraint=models.UniqueConstraint(fields=('tipoeq', 'marcaeq'), name='unique_tipoeq_marcaeq'),
        ),
    ]
