# Generated by Django 5.1.7 on 2025-03-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_settings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='marcaequipo',
            name='unique_tipoeq_marcaeq',
        ),
        migrations.AlterField(
            model_name='marcaequipo',
            name='marcaeq',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.RemoveField(
            model_name='marcaequipo',
            name='tipoeq',
        ),
        migrations.AddField(
            model_name='marcaequipo',
            name='tipoeq',
            field=models.ManyToManyField(to='maq_settings.tipoequipo'),
        ),
    ]
