# Generated by Django 5.1.7 on 2025-04-19 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_settings', '0002_remove_marcaequipo_unique_tipoeq_marcaeq_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeccionEspecificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Sección',
                'verbose_name_plural': 'Secciones',
                'ordering': ['seccion'],
            },
        ),
        migrations.CreateModel(
            name='Especificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacion', models.CharField(max_length=150)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maq_settings.seccionespecificacion')),
            ],
            options={
                'verbose_name': 'Especificación',
                'verbose_name_plural': 'Especificaciones',
                'ordering': ['especificacion'],
            },
        ),
    ]
