# Generated by Django 5.1.7 on 2025-04-19 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maq_settings', '0003_seccionespecificacion_especificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='especificacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
