# Generated by Django 5.1.7 on 2025-04-20 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maq_settings', '0004_especificacion_activo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacion',
            name='activo',
        ),
    ]
